<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\Node;

class Menu extends Node
{
    protected $table = 'sys_function';
    //protected $dates = ['delete_time'];

    const CREATED_AT = 'created_time';
    const UPDATED_AT = 'updated_time';
    //const DELETED_AT = 'deleted_time';

    protected $guarded = ['id'];

    public function getParentIdName()
    {
        return 'father_id'; // TODO: Change the autogenerated stub
    }
}
