<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\Node;

class Menu extends Node
{
    protected $table = 'sys_function';
    //protected $dates = ['delete_time'];

    const CREATED_AT = 'created_time';
    const UPDATED_AT = 'updated_time';
    //const DELETED_AT = 'deleted_time';

    protected $guarded = ['id'];

    public function getParentIdName()
    {
        return 'father_id'; // TODO: Change the autogenerated stub
    }

    public function role()
    {
        return $this->belongsToMany('App\Models\Role', 'sys_role_function', 'sys_fun_id', 'sys_role_id');
    }

    public function parent()
    {
        return $this->belongsTo('App\Models\Menu', 'father_id','id');
    }
}
